config/routes.rb
Directory::Application.routes.draw do
  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :date_of_birth, :eye_color, :first_name, :hair_color, :height, :last_name, :middle_name, :sex, :weight

  def self.seed_data!
    genders = ["Male", "Female"]
    eye_colors = ["blue", "green", "brown"]
    hair_color = ["red", "blonde", "brown", "black"]
    inches = (37..65).to_a
    pounds= (35..200).to_a

    earliest_birthdate = Date.parse("1-9-1994")
    latest_birthdate = Date.parse("30-8-2007")
    birthdates = (earliest_birthdate..latest_birthdate).to_a


    500.times do
      Student.create(
          :first_name => Faker::Name.first_name,
          :middle_name => Faker::Name.first_name,
          :last_name => Faker::Name.last_name,
          :date_of_birth => birthdates.sample,
          :hair_color => hair_color.shuffle.first,
          :eye_color => eye_colors.shuffle.first,
          :height => inches.shuffle.first,
          :weight => pounds.shuffle.first,
          :sex => genders.shuffle.first
      )
    end
  end

  def self.tommy_smiths
    Student.where(:first_name => "Tommy", :last_name => "Smith")
  end

  def self.number_of_five_year_olds
    five = Date.today - 5.years
    year = five + 1.years

    Student.where(:date_of_birth => five..year).count
  end

  def self.number_of_six_year_olds
    six = Date.today - 6.years
    year = six + 1.years

    Student.where(:date_of_birth => six..year).count
  end

  def self.number_of_seven_to_nine_year_olds
    seven = Date.today - 7.years
    nine = seven + 2.years

    Student.where(:date_of_birth => seven..nine).count
  end

  def self.number_of_teenagers
    thirteen = Date.today - 13.years
    nineteen = thirteen + 6.years

    Student.where(:date_of_birth => thirteen..nineteen).count
  end

  def self.green_eye_students

    Student.where(:eye_color => "green").count
  end

  def self.any_students_with_same_first_names?
    Student.count(:group => :first_name, :having => "count(*) > 1").any?
  end

  def self.any_students_with_same_last_names?
    Student.count(:group => :last_name, :having => "count(*) > 1").any?
  end

  def self.number_of_male_students
    Student.where(:sex => "Male").count
  end

  def self.number_of_female_students
    Student.where(:sex => "Female").count
  end

  def self.redhead_students_first_names
    Student.where(:hair_color => "red").map(&:first_name)
  end

  def self.birthdates_within_thirty_days
    thirty_days_later = Date.today - 30.days
    birthdate_range = Date.today..thirty_days_later
    Student.where(:date_of_birth => birthdate_range).order(:date_of_birth => :asc)
    #I need to minus the year on the birthdates (date_select :discard_year => true)
  end

  def self.students_ordered_by_birthdates
    earliest_birthdate = Date.parse("1-9-1994")
    latest_birthdate = Date.parse("30-8-2007")
    birthdates = (earliest_birthdate..latest_birthdate).to_a

    Student.where(:date_of_birth => birthdates).order(:date_of_birth => :asc)
  end

  def self.output_name_and_age
    Student.order("date_of_birth ASC").each do |student|
      puts "#{student.first_name} #{student.last_name} is #{(Time.now.year - student.date_of_birth.year)} years old."
    end
  end

  def self.list_by_eye_color
    puts "Blue eyes"
    Student.where(:eye_color => "blue").map(&:first_name)
    puts "Green eyes"
    Student.where(:eye_color => "green").map(&:first_name)
    puts "Brown eyes"
    Student.where(:eye_color => "brown").map(&:first_name)
  end

    #eyes = Student.select("first_name, eye_color").group("eye_color")
    #eyes.each do |eye|
    #  puts "*" * 50
    #  puts eye.eye_color.upcase
    #  puts "*" * 50
    #  student = Student.select("first_name, eye_color")
    #  students.each do |student|
    #    puts student.first_name if student.eye_color == eye.eye_color
    #  end
    #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directory</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :hair_color %><br />
    <%= f.text_field :hair_color %>
  </div>
  <div class="field">
    <%= f.label :eye_color %><br />
    <%= f.text_field :eye_color %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Middle name</th>
    <th>Last name</th>
    <th>Date of birth</th>
    <th>Hair color</th>
    <th>Eye color</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Sex</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.first_name %></td>
    <td><%= student.middle_name %></td>
    <td><%= student.last_name %></td>
    <td><%= student.date_of_birth %></td>
    <td><%= student.hair_color %></td>
    <td><%= student.eye_color %></td>
    <td><%= student.height %></td>
    <td><%= student.weight %></td>
    <td><%= student.sex %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @student.first_name %>
</p>

<p>
  <b>Middle name:</b>
  <%= @student.middle_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @student.last_name %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @student.date_of_birth %>
</p>

<p>
  <b>Hair color:</b>
  <%= @student.hair_color %>
</p>

<p>
  <b>Eye color:</b>
  <%= @student.eye_color %>
</p>

<p>
  <b>Height:</b>
  <%= @student.height %>
</p>

<p>
  <b>Weight:</b>
  <%= @student.weight %>
</p>

<p>
  <b>Sex:</b>
  <%= @student.sex %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>